spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_reservation?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Zch12.1159357
  
  redis:
    host: localhost
    port: 6379
